Include deconv_layer.hpp to layer_factory.cpp
Fix the '‘DeconvolutionLayer’ does not name a type' error.
Intel Caffe add new DeconvolutionLayer into layer_factory, but somehow the definition file has not been included. DeconvolutionLayer is defined in 'include/caffe/layers/deconv_layer.hpp'.
Detail:
'src/caffe/layer_factory.cpp:200:43: error: ‘DeconvolutionLayer’ does not name a type'
This error will occur while building Intel Caffe from the Source.